import io
import pandas as pd
from datetime import datetime
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

# ── Palette ─────────────────────────────────────────────────────────────────
DARK   = RGBColor(0x0F, 0x17, 0x2A)
BLUE   = RGBColor(0x25, 0x63, 0xEB)
PURPLE = RGBColor(0x6D, 0x28, 0xD9)
CYAN   = RGBColor(0x08, 0x91, 0xB2)
GREEN  = RGBColor(0x15, 0x80, 0x3D)
WHITE  = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT  = RGBColor(0xE2, 0xE8, 0xF0)
GRAY   = RGBColor(0x94, 0xA3, 0xB8)
HEADER_BG = RGBColor(0x1D, 0x4E, 0xD8)
ROW_ALT   = RGBColor(0x1A, 0x22, 0x38)
CARD_BG   = RGBColor(0x16, 0x1D, 0x33)

SLIDE_W = Inches(13.333)
SLIDE_H = Inches(7.5)
ACCENTS = [BLUE, PURPLE, CYAN, GREEN]


def _fill(shape, color):
    shape.fill.solid()
    shape.fill.fore_color.rgb = color
    shape.line.fill.background()


def _add_bg(slide, color=DARK):
    rect = slide.shapes.add_shape(1, 0, 0, SLIDE_W, SLIDE_H)
    _fill(rect, color)
    slide.shapes._spTree.remove(rect._element)
    slide.shapes._spTree.insert(2, rect._element)


def _text(slide, left, top, width, height, text, size=18, color=WHITE,
          bold=False, align=PP_ALIGN.LEFT, italic=False, font="Calibri"):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.italic = italic
    run.font.color.rgb = color
    run.font.name = font
    return box


def _fmt_val(v, col=""):
    cl = col.lower()
    if pd.isna(v):
        return "—"
    if isinstance(v, (int, float)):
        if any(k in cl for k in ("year", "month", "rank", "qtr", "quarter", "day")):
            return str(int(v))
        if any(k in cl for k in ("pct", "percent", "growth", "rate", "margin")):
            return f"{v:,.2f}%"
        if float(v).is_integer():
            return f"{int(v):,}"
        return f"{v:,.2f}"
    if hasattr(v, "date"):
        return str(v.date())
    return str(v)


# ── Slides ──────────────────────────────────────────────────────────────────
def _title_slide(prs, title, subtitle):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, DARK)
    band = slide.shapes.add_shape(1, 0, Inches(2.4), SLIDE_W, Inches(2.7))
    _fill(band, BLUE)
    _text(slide, Inches(0.8), Inches(2.7), Inches(11.7), Inches(1.2),
          title, size=40, bold=True, align=PP_ALIGN.CENTER)
    _text(slide, Inches(0.8), Inches(3.9), Inches(11.7), Inches(0.8),
          subtitle, size=16, color=LIGHT, align=PP_ALIGN.CENTER)
    _text(slide, Inches(0.8), Inches(6.6), Inches(11.7), Inches(0.5),
          "Generated by InsightIQ  ·  AI-Powered Business Intelligence Assistant",
          size=11, color=GRAY, align=PP_ALIGN.CENTER, italic=True)
    return slide


def _kpi_cards_slide(prs, stats: dict):
    if not stats:
        return
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, DARK)
    _text(slide, Inches(0.7), Inches(0.4), Inches(12), Inches(0.8),
          "Key Metrics at a Glance", size=28, bold=True, color=RGBColor(0x93,0xC5,0xFD))
    items = list(stats.items())[:4]
    n = len(items)
    gap = Inches(0.3)
    total_gap = gap * (n + 1)
    card_w = Emu(int((SLIDE_W - total_gap) / n))
    top = Inches(2.4)
    card_h = Inches(2.6)
    x = gap
    for i, (label, value) in enumerate(items):
        card = slide.shapes.add_shape(1, x, top, card_w, card_h)
        _fill(card, ACCENTS[i % len(ACCENTS)])
        vb = slide.shapes.add_textbox(x, top + Inches(0.6), card_w, Inches(1.0))
        vp = vb.text_frame.paragraphs[0]; vp.alignment = PP_ALIGN.CENTER
        r = vp.add_run(); r.text = str(value)
        r.font.size = Pt(34); r.font.bold = True; r.font.color.rgb = WHITE
        lb = slide.shapes.add_textbox(x, top + Inches(1.7), card_w, Inches(0.7))
        lp = lb.text_frame.paragraphs[0]; lp.alignment = PP_ALIGN.CENTER
        lr = lp.add_run(); lr.text = label.upper()
        lr.font.size = Pt(12); lr.font.color.rgb = WHITE
        x = Emu(int(x) + int(card_w) + int(gap))
    return slide


def _section_slide(prs, heading, explanation, df, accent):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _add_bg(slide, DARK)
    # Accent bar + heading
    bar = slide.shapes.add_shape(1, 0, 0, Inches(0.18), SLIDE_H)
    _fill(bar, accent)
    _text(slide, Inches(0.5), Inches(0.35), Inches(12.4), Inches(0.8),
          heading, size=26, bold=True, color=RGBColor(0x93,0xC5,0xFD))

    # Explanation (trim to keep slide clean)
    exp = (explanation or "").strip()
    if len(exp) > 420:
        exp = exp[:417] + "..."
    _text(slide, Inches(0.5), Inches(1.25), Inches(12.3), Inches(1.3),
          exp, size=13, color=LIGHT)

    # Table
    if df is not None and not df.empty:
        max_rows = 9
        max_cols = 6
        show = df.iloc[:max_rows, :max_cols]
        rows = len(show) + 1
        cols = len(show.columns)
        top = Inches(2.7)
        height = Inches(min(4.2, 0.45 * rows))
        tbl_shape = slide.shapes.add_table(rows, cols, Inches(0.5), top,
                                           Inches(12.3), height)
        table = tbl_shape.table
        # header
        for c, col in enumerate(show.columns):
            cell = table.cell(0, c)
            cell.text = str(col).replace("_", " ").upper()
            cell.fill.solid(); cell.fill.fore_color.rgb = HEADER_BG
            pr = cell.text_frame.paragraphs[0]; pr.alignment = PP_ALIGN.CENTER
            for run in pr.runs:
                run.font.size = Pt(11); run.font.bold = True; run.font.color.rgb = WHITE
        # body
        for r in range(len(show)):
            for c, col in enumerate(show.columns):
                cell = table.cell(r + 1, c)
                cell.text = _fmt_val(show.iloc[r, c], col)
                cell.fill.solid()
                cell.fill.fore_color.rgb = ROW_ALT if r % 2 == 0 else CARD_BG
                pr = cell.text_frame.paragraphs[0]
                for run in pr.runs:
                    run.font.size = Pt(10); run.font.color.rgb = LIGHT
    return slide


def generate_ppt(title: str, sections: list, summary_stats: dict = None,
                 username: str = "User") -> bytes:
    """
    sections = [{"heading","explanation","df"}]
    Returns .pptx bytes.
    """
    prs = Presentation()
    prs.slide_width = SLIDE_W
    prs.slide_height = SLIDE_H

    generated_at = datetime.now().strftime("%B %d, %Y")
    _title_slide(prs, title, f"{generated_at}  ·  Prepared by {username}")
    if summary_stats:
        _kpi_cards_slide(prs, summary_stats)
    for i, sec in enumerate(sections):
        _section_slide(prs, sec.get("heading", "Section"),
                       sec.get("explanation", ""), sec.get("df"),
                       ACCENTS[i % len(ACCENTS)])

    buf = io.BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf.getvalue()
